{
  imports = [
    ./bootloader.nix
    ./powerManagement.nix
    ./wireless.nix
    #./wayland.nix
    ./syncthing.nix
    ./kdePlasma.nix
    ./media.nix
    ./suspendThenHibernate.nix
    ./hardware-configuration.nix
    ./tzLocale.nix
    ./users.nix
    ./virt.nix
    ./miscNixStuff.nix
    ./nerdFonts.nix
    ./nixos-cli.nix
    ./lanzaboote.nix
    ./printing.nix
    ./yubikey.nix
    ./steam.nix
  ];
}
