# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "mem_sleep_default=deep" ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f22a8948-fbb6-42a6-b0a0-ccc88d8a07a6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f22a8948-fbb6-42a6-b0a0-ccc88d8a07a6".device = "/dev/disk/by-uuid/f22a8948-fbb6-42a6-b0a0-ccc88d8a07a6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1C48-C569";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-02460964-8051-4381-aeae-a2b71a2c2f2d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
