{
  imports = [
    ./bootloader.nix
    ./graphics.nix
    ./powerManagement.nix
    ./wireless.nix
    #./hyprland.nix
    ./syncthing.nix
    ./kdePlasma.nix
    ./pulseAudio.nix
    ./suspendThenHibernate.nix
    ./spicetify.nix
    ./hardware-configuration.nix
    ./tzLocale.nix
    ./users.nix
    ./virt.nix
    ./miscNixStuff.nix
    ./nerdFonts.nix
    ./nixos-cli.nix
  ];
}
