# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f687d29b-d636-432a-98bb-af7f6e3dc226";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-33fd1822-bf27-4a3e-a8e7-1c703185a503".device = "/dev/disk/by-uuid/33fd1822-bf27-4a3e-a8e7-1c703185a503";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/653C-4F14";                                                                                                                                                                    
      fsType = "vfat";                                                                                                                                                                                           
      options = [ "fmask=0077" "dmask=0077" ];                                                                                                                                                                   
    };                                                                                                                                                                                                           
                                                                                                                                                                                                                 
  swapDevices =                                                                                                                                                                                                  
    [ { device = "/dev/disk/by-uuid/7b97e697-298b-4af4-b8ff-8b0bef8d7520"; }                                                                                                                                     
    ];                                                                                                                                                                                                           
                                                                                                                                                                                                                 
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking                                                                                                                         
  # (the default) this is the recommended approach. When using systemd-networkd it's                                                                                                                             
  # still possible to use this option, but it's recommended to use it in conjunction                                                                                                                             
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.                                                                                                                   
  networking.useDHCP = lib.mkDefault true;                                                                                                                                                                       
  # networking.interfaces.wlp59s0.useDHCP = lib.mkDefault true;                                                                                                                                                  
                                                                                                                                                                                                                 
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";                                                                                                                                                           
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;                                                                                                              
}
